// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6bbXvfqULo1LwRyPbpSYlZ_Dm1C77E7M',
    appId: '1:9939219864:web:47f47fb92485860469e7ed',
    messagingSenderId: '9939219864',
    projectId: 'nova-system',
    authDomain: 'nova-system.firebaseapp.com',
    storageBucket: 'nova-system.appspot.com',
    measurementId: 'G-RRTQ04Z5C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPhAvXOcmvkhX2F8WYQRv1AuutVzG51M0',
    appId: '1:9939219864:android:25a3b92a51e525d269e7ed',
    messagingSenderId: '9939219864',
    projectId: 'nova-system',
    storageBucket: 'nova-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR7VmCQ8sIW3hw7nFjz_hQkUHyIsOGCWA',
    appId: '1:9939219864:ios:b6663fcd74596b9a69e7ed',
    messagingSenderId: '9939219864',
    projectId: 'nova-system',
    storageBucket: 'nova-system.appspot.com',
    androidClientId: '9939219864-4u6unhlaebgq3tu8kahenhu64oe4i2dp.apps.googleusercontent.com',
    iosClientId: '9939219864-r3ekp661b5q5ia69pmrfakvj8ajc1e9d.apps.googleusercontent.com',
    iosBundleId: 'com.garv.nova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR7VmCQ8sIW3hw7nFjz_hQkUHyIsOGCWA',
    appId: '1:9939219864:ios:b6663fcd74596b9a69e7ed',
    messagingSenderId: '9939219864',
    projectId: 'nova-system',
    storageBucket: 'nova-system.appspot.com',
    androidClientId: '9939219864-4u6unhlaebgq3tu8kahenhu64oe4i2dp.apps.googleusercontent.com',
    iosClientId: '9939219864-r3ekp661b5q5ia69pmrfakvj8ajc1e9d.apps.googleusercontent.com',
    iosBundleId: 'com.garv.nova',
  );
}
