on: push
jobs: 
  build-macos: 
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'  
    - run: flutter pub get
    - run: flutter config --enable-macos-desktop
    - run: flutter build apk --release
    - run: flutter build appbundle --release
    - run: flutter build web --release
    - run: flutter build macos --release
    - name: 'Upload APK'
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: build/app/outputs/flutter-apk/app-release.apk
    - name: 'Upload Appbundle'
      uses: actions/upload-artifact@v2
      with:
        name: appbundle
        path: build/app/outputs/bundle/release/app-release.aab
    - name: 'Upload MacOS'
      uses: actions/upload-artifact@v2
      with:
        name: macos
        path: build/macos/Build/Products/
    - name: 'Upload Web'
      uses: actions/upload-artifact@v2
      with:
        name: web
        path: build/web/
  build-windows: 
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'  
    - run: flutter pub get
    - run: flutter config --enable-windows-desktop
    - run: flutter build windows --release
    - run: flutter pub run msix:create
    - name: 'Upload Windows'
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: build/windows/runner/Release/
  build-linux: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'  
    - run: flutter doctor
    - run: sudo apt-get update -y
    - run: sudo apt-get install -y ninja-build libgtk-3-dev
    - run: flutter doctor
    - run: flutter pub get
    - run: flutter config --enable-linux-desktop
    - run: flutter build linux --release
    - name: 'Upload Linux'
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: build/linux/x64/release/bundle/
