on: push
jobs: 
  build-macos: 
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
        flutter-version: '2.8.0'
    - run: flutter pub get
    - run: flutter config --enable-macos-desktop
    - run: flutter build apk --release
    - run: flutter build appbundle --release
    - run: flutter build web --release
    - run: flutter build macos --release
    - name: 'Upload APK'
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: build/app/outputs/flutter-apk/app-release.apk
    - name: 'Upload Appbundle'
      uses: actions/upload-artifact@v2
      with:
        name: appbundle
        path: build/app/outputs/bundle/release/app-release.aab
    - name: 'Upload MacOS'
      uses: actions/upload-artifact@v2
      with:
        name: macos
        path: build/macos/Build/Products/
    - name: 'Upload Web'
      uses: actions/upload-artifact@v2
      with:
        name: web
        path: build/web/
  build-windows: 
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - VS_VERSION: Visual Studio 16
            VS_VER: 2019
            SDK: release-1911 # gisinternals SDK version still to 2017
            MSVC_VER: 1920
            platform: x86
            PROJ_BRANCH: "7.2"
            LIBWEBP_URL: "https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.0.3-windows-x86.zip"
            LIBZSTD_URL: "https://github.com/facebook/zstd/releases/download/v1.4.5/zstd-v1.4.5-win32.zip"
            LIBDEFLATE_URL: "https://github.com/ebiggers/libdeflate/releases/download/v1.6/libdeflate-1.6-windows-i686-bin.zip"

    env:
        VS_VERSION: ${{ matrix.VS_VERSION }}
        VS_VER: ${{ matrix.VS_VER }}
        SDK: ${{ matrix.SDK }}
        MSVC_VER: ${{ matrix.MSVC_VER }}
        platform: ${{ matrix.platform }}
        PROJ_BRANCH: "${{ matrix.PROJ_BRANCH }}"
        LIBWEBP_URL: "${{ matrix.LIBWEBP_URL }}"
        LIBZSTD_URL: "${{ matrix.LIBZSTD_URL }}"
        LIBDEFLATE_URL: "${{ matrix.LIBDEFLATE_URL }}"
        APPVEYOR: true # to skip some tests
        PYTHON_VERSION: "3.7.9"

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
        flutter-version: '2.8.0'
    - run: flutter pub get
    - run: flutter config --enable-windows-desktop
    - run: flutter build windows --release
    - run: flutter pub run msix:create
    - name: 'Upload Windows'
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: build/windows/runner/Release/
  build-linux: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
        flutter-version: '2.8.0'
    - run: flutter doctor
    - run: sudo apt-get update -y
    - run: sudo apt-get install -y ninja-build libgtk-3-dev
    - run: flutter doctor
    - run: flutter pub get
    - run: flutter config --enable-linux-desktop
    - run: flutter build linux --release
    - name: 'Upload Linux'
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: build/linux/x64/release/bundle/
